USE [master]
GO

CREATE DATABASE [Geometry]
 GO
USE [Geometry]
GO

CREATE TABLE Line(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Point1_X] [int] NOT NULL,
	[Point1_Y] [int] NOT NULL,
	[Point2_X] [int] NOT NULL,
	[Point2_Y] [int] NOT NULL,
 CONSTRAINT [PK_Line] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
